name: labeler

on: [pull_request]

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Label the PR
    steps:
      - name: Pull request size labeler
        uses: codelytv/pr-size-labeler@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_max_size: '1'
          s_max_size: '2'
          m_max_size: '3'
          l_max_size: '4'
          fail_if_xl: 'true'
